### ISSUE TITLE
edited

### ISSUE THREAD

**Issue by FlotingDream** [qweasdd/manga-colorization-v2#1]
edited

**Comment by Roy-Bertoli** [comment]
Hi FlotingDream, why did you close the ghitub? I was using the colab you created and it worked very well, I would be grateful if you reopened it, thank you very much.

**Comment by FlotingDream** [comment]
![image](https://user-images.githubusercontent.com/50733815/179143112-127b0555-1495-4547-aae9-244f7cbc70f8.png)
Anyway, thanks for your attention!

**Comment by Roy-Bertoli** [comment]
Hi, can you help me in some way, it's a lifetime that I look for a program to color Italian comics \ manga for personal purposes since they are all in black and white, and the colab you created worked really well on these comics \ manga, on the your ghitub you don't have the voice "issues" and I don't know how to contact you, I'm on windows 10 and I don't understand anything about the programs you use, I hope you can do something, thanks.

**Comment by FlotingDream** [comment]
> Hi, can you help me in some way, it's a lifetime that I look for a program to color Italian comics \ manga for personal purposes since they are all in black and white, and the colab you created worked really well on these comics \ manga, on the your ghitub you don't have the voice "issues" and I don't know how to contact you, I'm on windows 10 and I don't understand anything about the programs you use, I hope you can do something, thanks.

Leave your email, I will send you a copy.

**Comment by Roy-Bertoli** [comment]
roy00000001@gmail.com

**Comment by Roy-Bertoli** [comment]
***@***.***

Il giorno sab 16 lug 2022 alle ore 07:32 FlotingDream <
***@***.***> ha scritto:

**Comment by Roy-Bertoli** [comment]
Ciao FlotingDream, la mia email è:  roy00000001@gmail.com

**Comment by FlotingDream** [comment]
> Hi FlotingDream, my email is: [roy00000001@gmail.com](mailto:roy00000001@gmail.com)

<html>
<body>


收件人： | roy00000001@gmail.com
-- | --
日期： | 2022年7月16日 14:35


</body>
</html>
